import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const copyPlugin = {
  name: "copy-plugin",
  setup(build) {
    build.onEnd(() => {
      const outdir = path.dirname(build.initialOptions.outfile);
      // Ensure dist directory exists
      if (!fs.existsSync(outdir)) {
        fs.mkdirSync(outdir, { recursive: true });
      }
      // Copy manifest.json and styles.css
      const filesToCopy = ["manifest.json", "styles.css"];
      for (const file of filesToCopy) {
        if (fs.existsSync(file)) {
          fs.copyFileSync(file, path.join(outdir, file));
        }
      }
    });
  },
};

const staticAssetsPlugin = {
  name: "static-assets-plugin",
  setup(build) {
    build.onLoad({ filter: /.+/ }, args => {
      return {
        watchFiles: ["styles.css", "esbuild.config.mjs"],
      };
    });
  },
};

const prod = process.argv[2] === "production";

const buildOptions = {
  banner: {
    js: banner,
  },
  minify: prod ? true : false,
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", "codemirror", "@codemirror/view", ...builtins],
  format: "cjs",
  target: "ES2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "dist/main.js",
  plugins: [
    staticAssetsPlugin,
    copyPlugin,
  ],
};

(async () => {
  if (prod) {
    await esbuild.build(buildOptions);
  } else {
    const ctx = await esbuild.context(buildOptions);
    await ctx.watch();
    console.log("Watching for changes...");
  }
})().catch(() => process.exit(1));

